Change testing strategy. No idea why it fixes missing libexpat (#12)
Fixes:
ImportError: libexpat.so.0: cannot open shared object file: No such file or directory

On x86_64 manylinux1 test runs